### ISSUE TITLE
Improve win32 compatibility

### ISSUE THREAD

**Issue by eroncardoso88** [nguyenbatranvan/nx-vite-federation#1]
## Versions
nx-vite-federation: sha 84580e72ae78f0f8eb05ebf32d920aa36a5fdccf
OS: Windows 11
terminal: bash
npm: 9.7.2
node: 20.4.0

`spawn` config isn't setup the best way in `scripts/start-federation.js`

![image](https://github.com/nguyenbatranvan/nx-vite-federation/assets/42578522/956f191a-cecd-4441-9ed0-4ab89be96e38)

## Fix Suggestion:

Add 

```
{stdio: 'inherit', shell: true}
```

to all `spawn()` functions in the file.

lines: 

60,
62,
66,
68

![image](https://github.com/nguyenbatranvan/nx-vite-federation/assets/42578522/1a26c2d3-5245-4197-8b47-b6aaed9492f7)

That's a very cool project, I'm looking forward to use and maybe even to contribute.

**Comment by nguyenbatranvan** [comment]
> ## Versions
> nx-vite-federation: sha [84580e7](https://github.com/nguyenbatranvan/nx-vite-federation/commit/84580e72ae78f0f8eb05ebf32d920aa36a5fdccf) OS: Windows 11 terminal: bash npm: 9.7.2 node: 20.4.0
> 
> `spawn` config isn't setup the best way in `scripts/start-federation.js`
> 
> ![image](https://user-images.githubusercontent.com/42578522/260324427-956f191a-cecd-4441-9ed0-4ab89be96e38.png)
> 
> ## Fix Suggestion:
> Add
> 
> ```
> {stdio: 'inherit', shell: true}
> ```
> 
> to all `spawn()` functions in the file.
> 
> lines:
> 
> 60, 62, 66, 68
> 
> ![image](https://user-images.githubusercontent.com/42578522/260324630-1a26c2d3-5245-4197-8b47-b6aaed9492f7.png)
> 
> That's a very cool project, I'm looking forward to use and maybe even to contribute.

Thanks a lot for your feedback, I'll be back after finishing some of my work soon!!

**Comment by nguyenbatranvan** [comment]
problem has been resolved. Please check out the repo!!
